events {}

http {

    upstream backend {
        server app1:8081;
    }

    server {
        listen 80;

        location / {

            proxy_pass http://backend;

            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
        }
    }
}